In [100]:
import pandas as pd

spread_2018 = pd.read_csv("../2018_spreads/2018_playoffs_spreads.csv")
spread_2018['Year'] = '2018'
spread_2019 = pd.read_csv("../2019_spreads/2019_playoffs_spreads.csv")
spread_2019['Year'] = '2019'
spread_2020 = pd.read_csv("../2020_spreads/2020_playoffs_spreads.csv")
spread_2020['Year'] = '2020'
spread_2021 = pd.read_csv("../2021_spreads/2021_playoffs_spreads.csv")
spread_2021['Year'] = '2021'
spread_2022 = pd.read_csv("../2022_spreads/2022_playoffs_spreads.csv")
spread_2022['Year'] = '2022'

In [101]:
# Combine them
spread_df = pd.concat(
    [spread_2018, spread_2019, spread_2020, spread_2021, spread_2022],
    ignore_index=True
)

In [102]:
spread_df

,Date,Rot,VH,Team,1st,2nd,3rd,4th,Final,Open,Close,ML,2H,Year
0,414,501,V,SanAntonio,17,24,22,29,92,210,205.5,300,105,2018
1,414,502,H,GoldenState,28,29,29,27,113,8,8,-400,0.5,2018
2,414,503,V,Washington,23,36,26,21,106,211,214,275,106,2018
3,414,504,H,Toronto,28,27,31,28,114,7.5,7.5,-350,7,2018
4,414,505,V,Miami,35,25,18,25,103,210,214,200,105.5,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,610,524,H,Boston,28,26,24,19,97,2.5,4.0,-165,1,2022
834,613,525,V,Boston,16,23,35,20,94,212.5,211.0,145,2.5,2022
835,613,526,H,Golden State,27,24,24,29,104,3.5,4.0,-165,107.5,2022
836,616,527,V,Golden State,27,27,22,27,103,212.5,211.5,155,103.5,2022
837,616,528,H,Boston,22,17,27,24,90,2.5,4.0,-175,5.5,2022

In [103]:
# Ensure Date is 4 digits and Year is int
spread_df['Date'] = spread_df['Date'].astype(str).str.zfill(4)
spread_df['Year'] = spread_df['Year'].astype(str)

In [104]:
# Combine into full date string
spread_df['GameDate'] = pd.to_datetime(spread_df['Year'] + spread_df['Date'], format='%Y%m%d', errors='coerce')

In [105]:
spread_df

,Date,Rot,VH,Team,1st,2nd,3rd,4th,Final,Open,Close,ML,2H,Year,GameDate
0,0414,501,V,SanAntonio,17,24,22,29,92,210,205.5,300,105,2018,2018-04-14
1,0414,502,H,GoldenState,28,29,29,27,113,8,8,-400,0.5,2018,2018-04-14
2,0414,503,V,Washington,23,36,26,21,106,211,214,275,106,2018,2018-04-14
3,0414,504,H,Toronto,28,27,31,28,114,7.5,7.5,-350,7,2018,2018-04-14
4,0414,505,V,Miami,35,25,18,25,103,210,214,200,105.5,2018,2018-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,0610,524,H,Boston,28,26,24,19,97,2.5,4.0,-165,1,2022,2022-06-10
834,0613,525,V,Boston,16,23,35,20,94,212.5,211.0,145,2.5,2022,2022-06-13
835,0613,526,H,Golden State,27,24,24,29,104,3.5,4.0,-165,107.5,2022,2022-06-13
836,0616,527,V,Golden State,27,27,22,27,103,212.5,211.5,155,103.5,2022,2022-06-16
837,0616,528,H,Boston,22,17,27,24,90,2.5,4.0,-175,5.5,2022,2022-06-16

In [106]:
team_name_to_abbreviation = {
    "Atlanta": "ATL",
    "Boston": "BOS",
    "Brooklyn": "BKN",
    "Charlotte": "CHA",
    "Chicago": "CHI",
    "Cleveland": "CLE",
    "Dallas": "DAL",
    "Denver": "DEN",
    "Detroit": "DET",
    "GoldenState": "GSW",
    "Houston": "HOU",
    "Indiana": "IND",
    "LAClippers": "LAC",
    "LALakers": "LAL",
    "Memphis": "MEM",
    "Miami": "MIA",
    "Milwaukee": "MIL",
    "Minnesota": "MIN",
    "NewOrleans": "NOP",
    "NewYork": "NYK",
    "OklahomaCity": "OKC",
    "Orlando": "ORL",
    "Philadelphia": "PHI",
    "Phoenix": "PHX",
    "Portland": "POR",
    "Sacramento": "SAC",
    "SanAntonio": "SAS",
    "Toronto": "TOR",
    "Utah": "UTA",
    "Washington": "WAS"
}

In [107]:
spread_df['TEAM_ABBREVIATION'] = spread_df['Team'].str.replace(" ", "").map(team_name_to_abbreviation)
spread_df

,Date,Rot,VH,Team,1st,2nd,3rd,4th,Final,Open,Close,ML,2H,Year,GameDate,TEAM_ABBREVIATION
0,0414,501,V,SanAntonio,17,24,22,29,92,210,205.5,300,105,2018,2018-04-14,SAS
1,0414,502,H,GoldenState,28,29,29,27,113,8,8,-400,0.5,2018,2018-04-14,GSW
2,0414,503,V,Washington,23,36,26,21,106,211,214,275,106,2018,2018-04-14,WAS
3,0414,504,H,Toronto,28,27,31,28,114,7.5,7.5,-350,7,2018,2018-04-14,TOR
4,0414,505,V,Miami,35,25,18,25,103,210,214,200,105.5,2018,2018-04-14,MIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,0610,524,H,Boston,28,26,24,19,97,2.5,4.0,-165,1,2022,2022-06-10,BOS
834,0613,525,V,Boston,16,23,35,20,94,212.5,211.0,145,2.5,2022,2022-06-13,BOS
835,0613,526,H,Golden State,27,24,24,29,104,3.5,4.0,-165,107.5,2022,2022-06-13,GSW
836,0616,527,V,Golden State,27,27,22,27,103,212.5,211.5,155,103.5,2022,2022-06-16,GSW
837,0616,528,H,Boston,22,17,27,24,90,2.5,4.0,-175,5.5,2022,2022-06-16,BOS

In [108]:
spread_df['GameDate'].info

<bound method Series.info of 0     2018-04-14
1     2018-04-14
2     2018-04-14
3     2018-04-14
4     2018-04-14
         ...
833   2022-06-10
834   2022-06-13
835   2022-06-13
836   2022-06-16
837   2022-06-16
Name: GameDate, Length: 838, dtype: datetime64[ns]>

In [109]:
spread_df['HOME_AWAY'] = spread_df['VH'].map({'H': 'Home', 'V': 'Away'})
spread_df

,Date,Rot,VH,Team,1st,2nd,3rd,4th,Final,Open,Close,ML,2H,Year,GameDate,TEAM_ABBREVIATION,HOME_AWAY
0,0414,501,V,SanAntonio,17,24,22,29,92,210,205.5,300,105,2018,2018-04-14,SAS,Away
1,0414,502,H,GoldenState,28,29,29,27,113,8,8,-400,0.5,2018,2018-04-14,GSW,Home
2,0414,503,V,Washington,23,36,26,21,106,211,214,275,106,2018,2018-04-14,WAS,Away
3,0414,504,H,Toronto,28,27,31,28,114,7.5,7.5,-350,7,2018,2018-04-14,TOR,Home
4,0414,505,V,Miami,35,25,18,25,103,210,214,200,105.5,2018,2018-04-14,MIA,Away
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,0610,524,H,Boston,28,26,24,19,97,2.5,4.0,-165,1,2022,2022-06-10,BOS,Home
834,0613,525,V,Boston,16,23,35,20,94,212.5,211.0,145,2.5,2022,2022-06-13,BOS,Away
835,0613,526,H,Golden State,27,24,24,29,104,3.5,4.0,-165,107.5,2022,2022-06-13,GSW,Home
836,0616,527,V,Golden State,27,27,22,27,103,212.5,211.5,155,103.5,2022,2022-06-16,GSW,Away
837,0616,528,H,Boston,22,17,27,24,90,2.5,4.0,-175,5.5,2022,2022-06-16,BOS,Home

In [110]:
team_games_merged = pd.read_csv('../Merges/team_with_game_metadata.csv')
team_games_merged

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,MATCHUP,WL,MIN,FGM,FGA,...,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,GAME_DATE,HOME_AWAY
0,42009,1610612749,MIL,Milwaukee Bucks,40900121,MIL @ ATL,L,240,37,82,...,11,11,1,14,18,92,-10,0,2010-04-17,Away
1,42009,1610612743,DEN,Denver Nuggets,40900171,DEN vs. UTA,W,240,48,84,...,29,6,3,8,25,126,13,0,2010-04-17,Home
2,42009,1610612741,CHI,Chicago Bulls,40900101,CHI @ CLE,L,240,37,87,...,19,12,4,14,19,83,-13,0,2010-04-17,Away
3,42009,1610612762,UTA,Utah Jazz,40900171,UTA @ DEN,L,240,41,75,...,26,4,6,10,25,113,-13,0,2010-04-17,Away
4,42009,1610612737,ATL,Atlanta Hawks,40900121,ATL vs. MIL,W,240,41,76,...,18,8,11,13,17,102,10,0,2010-04-17,Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,42023,1610612738,BOS,Boston Celtics,42300403,BOS @ DAL,W,240,38,82,...,26,4,6,9,19,106,7,1,2024-06-12,Away
2500,42023,1610612742,DAL,Dallas Mavericks,42300404,DAL vs. BOS,W,240,46,91,...,21,7,2,9,17,122,38,1,2024-06-14,Home
2501,42023,1610612738,BOS,Boston Celtics,42300404,BOS @ DAL,L,240,29,80,...,18,2,5,14,19,84,-38,1,2024-06-14,Away
2502,42023,1610612742,DAL,Dallas Mavericks,42300405,DAL @ BOS,L,240,35,78,...,18,4,4,13,20,88,-18,1,2024-06-17,Away
2503,42023,1610612738,BOS,Boston Celtics,42300405,BOS vs. DAL,W,240,38,89,...,25,9,2,9,15,106,18,1,2024-06-17,Home

In [111]:
team_games_merged['GAME_DATE'] = pd.to_datetime(team_games_merged['GAME_DATE'])

In [112]:
team_with_spreads = pd.merge(
    team_games_merged,
    spread_df,
    how='inner',
    left_on=['TEAM_ABBREVIATION', 'GAME_DATE', 'HOME_AWAY'],
    right_on=['TEAM_ABBREVIATION', 'GameDate', 'HOME_AWAY'],
    
)

In [113]:
team_with_spreads

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,MATCHUP,WL,MIN,FGM,FGA,...,2nd,3rd,4th,Final,Open,Close,ML,2H,Year,GameDate
0,42017,1610612764,WAS,Washington Wizards,41700101,WAS @ TOR,L,240,41,86,...,36,26,21,106,211,214,275,106,2018,2018-04-14
1,42017,1610612755,PHI,Philadelphia 76ers,41700121,PHI vs. MIA,W,240,45,95,...,27,34,40,130,6.5,6,-250,6,2018,2018-04-14
2,42017,1610612748,MIA,Miami Heat,41700121,MIA @ PHI,L,240,35,77,...,25,18,25,103,210,214,200,105.5,2018,2018-04-14
3,42017,1610612744,GSW,Golden State Warriors,41700151,GSW vs. SAS,W,240,44,81,...,29,29,27,113,8,8,-400,0.5,2018,2018-04-14
4,42017,1610612740,NOP,New Orleans Pelicans,41700161,NOP @ POR,W,240,41,86,...,24,30,22,97,216,217,190,106,2018,2018-04-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,42021,1610612744,GSW,Golden State Warriors,42100404,GSW @ BOS,W,240,40,91,...,22,30,28,107,212.5,213.5,145,105.5,2022,2022-06-10
666,42021,1610612744,GSW,Golden State Warriors,42100405,GSW vs. BOS,W,240,41,88,...,24,24,29,104,3.5,4.0,-165,107.5,2022,2022-06-13
667,42021,1610612738,BOS,Boston Celtics,42100405,BOS @ GSW,L,240,31,75,...,23,35,20,94,212.5,211.0,145,2.5,2022,2022-06-13
668,42021,1610612744,GSW,Golden State Warriors,42100406,GSW @ BOS,W,240,38,92,...,27,22,27,103,212.5,211.5,155,103.5,2022,2022-06-16
669,42021,1610612738,BOS,Boston Celtics,42100406,BOS vs. GSW,L,240,34,80,...,17,27,24,90,2.5,4.0,-175,5.5,2022,2022-06-16

In [114]:
team_with_spreads.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE', 'GAME_DATE',
       'HOME_AWAY', 'Date', 'Rot', 'VH', 'Team', '1st', '2nd', '3rd', '4th',
       'Final', 'Open', 'Close', 'ML', '2H', 'Year', 'GameDate'],
      dtype='object')

In [115]:
team_with_spreads.drop(columns=['GameDate'], inplace=True)
team_with_spreads.drop(columns=['Date'], inplace=True)
team_with_spreads

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,MATCHUP,WL,MIN,FGM,FGA,...,1st,2nd,3rd,4th,Final,Open,Close,ML,2H,Year
0,42017,1610612764,WAS,Washington Wizards,41700101,WAS @ TOR,L,240,41,86,...,23,36,26,21,106,211,214,275,106,2018
1,42017,1610612755,PHI,Philadelphia 76ers,41700121,PHI vs. MIA,W,240,45,95,...,29,27,34,40,130,6.5,6,-250,6,2018
2,42017,1610612748,MIA,Miami Heat,41700121,MIA @ PHI,L,240,35,77,...,35,25,18,25,103,210,214,200,105.5,2018
3,42017,1610612744,GSW,Golden State Warriors,41700151,GSW vs. SAS,W,240,44,81,...,28,29,29,27,113,8,8,-400,0.5,2018
4,42017,1610612740,NOP,New Orleans Pelicans,41700161,NOP @ POR,W,240,41,86,...,21,24,30,22,97,216,217,190,106,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,42021,1610612744,GSW,Golden State Warriors,42100404,GSW @ BOS,W,240,40,91,...,27,22,30,28,107,212.5,213.5,145,105.5,2022
666,42021,1610612744,GSW,Golden State Warriors,42100405,GSW vs. BOS,W,240,41,88,...,27,24,24,29,104,3.5,4.0,-165,107.5,2022
667,42021,1610612738,BOS,Boston Celtics,42100405,BOS @ GSW,L,240,31,75,...,16,23,35,20,94,212.5,211.0,145,2.5,2022
668,42021,1610612744,GSW,Golden State Warriors,42100406,GSW @ BOS,W,240,38,92,...,27,27,22,27,103,212.5,211.5,155,103.5,2022
669,42021,1610612738,BOS,Boston Celtics,42100406,BOS vs. GSW,L,240,34,80,...,22,17,27,24,90,2.5,4.0,-175,5.5,2022

In [116]:
# Step 1: Standardize matchup strings so both teams have the same series ID
def get_series_id(row):
    teams = sorted(row['MATCHUP'].replace('@', 'vs.').replace('vs.', '').split())
    return f"{teams[0]}_vs_{teams[1]}_{row['SEASON_ID']}"

team_with_spreads['SERIES_ID'] = team_with_spreads.apply(get_series_id, axis=1)

# Step 2: Sort by date to ensure cumulative logic works
team_with_spreads = team_with_spreads.sort_values(by=['SERIES_ID', 'GAME_DATE'])

# Step 3: Create SERIES_WINS: cumulative wins per team in each series
team_with_spreads['SERIES_WINS'] = team_with_spreads.groupby(['SERIES_ID', 'TEAM_ABBREVIATION'])['WL'].transform(lambda x: (x == 'W').cumsum())
team_with_spreads

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,MATCHUP,WL,MIN,FGM,FGA,...,3rd,4th,Final,Open,Close,ML,2H,Year,SERIES_ID,SERIES_WINS
509,42021,1610612737,ATL,Atlanta Hawks,42100101,ATL @ MIA,L,240,29,75,...,20,31,91,215.5,220.5,225,1,2022,ATL_vs_MIA_42021,0
511,42021,1610612748,MIA,Miami Heat,42100101,MIA vs. ATL,W,240,43,82,...,27,29,115,6,6.5,-265,107.5,2022,ATL_vs_MIA_42021,1
522,42021,1610612737,ATL,Atlanta Hawks,42100102,ATL @ MIA,L,240,41,87,...,22,29,105,217,221.0,270,107.5,2022,ATL_vs_MIA_42021,0
525,42021,1610612748,MIA,Miami Heat,42100102,MIA vs. ATL,W,240,38,79,...,31,28,115,7,8.0,-330,4.5,2022,ATL_vs_MIA_42021,2
538,42021,1610612737,ATL,Atlanta Hawks,42100103,ATL vs. MIA,W,240,41,80,...,16,34,111,220,222.0,105,108.5,2022,ATL_vs_MIA_42021,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,42017,1610612761,TOR,Toronto Raptors,41700104,TOR @ WAS,L,240,34,79,...,29,18,98,218.5,1.5,-125,105.5,2018,TOR_vs_WAS_42017,2
71,42017,1610612761,TOR,Toronto Raptors,41700105,TOR vs. WAS,W,240,38,82,...,31,29,108,7,7,-330,4.5,2018,TOR_vs_WAS_42017,3
76,42017,1610612764,WAS,Washington Wizards,41700105,WAS @ TOR,L,240,37,90,...,31,20,98,214,216,260,107,2018,TOR_vs_WAS_42017,2
81,42017,1610612764,WAS,Washington Wizards,41700106,WAS vs. TOR,L,240,32,79,...,25,14,92,1,214.5,120,106,2018,TOR_vs_WAS_42017,2
84,42017,1610612761,TOR,Toronto Raptors,41700106,TOR @ WAS,W,240,40,90,...,23,29,102,215,2,-140,2,2018,TOR_vs_WAS_42017,4

In [117]:
# Step 1: Create a key to represent each unique game instance (date + series)
team_with_spreads['GAME_KEY'] = (
    team_with_spreads['SERIES_ID'] + '_' + team_with_spreads['GAME_DATE'].astype(str)
)

# Step 2: Select relevant columns to self-merge for opponent lookup
opponent_wins_df = team_with_spreads[['GAME_KEY', 'TEAM_ABBREVIATION', 'SERIES_WINS']]
opponent_wins_df = opponent_wins_df.rename(columns={
    'TEAM_ABBREVIATION': 'OPPONENT_ABBREVIATION',
    'SERIES_WINS': 'OPPONENT_SERIES_WINS'
})

# Step 3: Merge to get opponent's SERIES_WINS
team_with_spreads = pd.merge(
    team_with_spreads,
    opponent_wins_df,
    on='GAME_KEY',
    how='left'
)

# Step 4: Remove rows where team and opponent are the same
team_with_spreads = team_with_spreads[
    team_with_spreads['TEAM_ABBREVIATION'] != team_with_spreads['OPPONENT_ABBREVIATION']
]

# Step 5: Create SERIES_STANDING string like "2–1"
team_with_spreads['SERIES_STANDING'] = (
    team_with_spreads['SERIES_WINS'].astype(str) + '–' +
    team_with_spreads['OPPONENT_SERIES_WINS'].astype(str)
)
team_with_spreads

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,MATCHUP,WL,MIN,FGM,FGA,...,Close,ML,2H,Year,SERIES_ID,SERIES_WINS,GAME_KEY,OPPONENT_ABBREVIATION,OPPONENT_SERIES_WINS,SERIES_STANDING
1,42021,1610612737,ATL,Atlanta Hawks,42100101,ATL @ MIA,L,240,29,75,...,220.5,225,1,2022,ATL_vs_MIA_42021,0,ATL_vs_MIA_42021_2022-04-17,MIA,1,0–1
2,42021,1610612748,MIA,Miami Heat,42100101,MIA vs. ATL,W,240,43,82,...,6.5,-265,107.5,2022,ATL_vs_MIA_42021,1,ATL_vs_MIA_42021_2022-04-17,ATL,0,1–0
5,42021,1610612737,ATL,Atlanta Hawks,42100102,ATL @ MIA,L,240,41,87,...,221.0,270,107.5,2022,ATL_vs_MIA_42021,0,ATL_vs_MIA_42021_2022-04-19,MIA,2,0–2
6,42021,1610612748,MIA,Miami Heat,42100102,MIA vs. ATL,W,240,38,79,...,8.0,-330,4.5,2022,ATL_vs_MIA_42021,2,ATL_vs_MIA_42021_2022-04-19,ATL,0,2–0
9,42021,1610612737,ATL,Atlanta Hawks,42100103,ATL vs. MIA,W,240,41,80,...,222.0,105,108.5,2022,ATL_vs_MIA_42021,1,ATL_vs_MIA_42021_2022-04-22,MIA,2,1–2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1330,42017,1610612761,TOR,Toronto Raptors,41700104,TOR @ WAS,L,240,34,79,...,1.5,-125,105.5,2018,TOR_vs_WAS_42017,2,TOR_vs_WAS_42017_2018-04-22,WAS,2,2–2
1333,42017,1610612761,TOR,Toronto Raptors,41700105,TOR vs. WAS,W,240,38,82,...,7,-330,4.5,2018,TOR_vs_WAS_42017,3,TOR_vs_WAS_42017_2018-04-25,WAS,2,3–2
1334,42017,1610612764,WAS,Washington Wizards,41700105,WAS @ TOR,L,240,37,90,...,216,260,107,2018,TOR_vs_WAS_42017,2,TOR_vs_WAS_42017_2018-04-25,TOR,3,2–3
1337,42017,1610612764,WAS,Washington Wizards,41700106,WAS vs. TOR,L,240,32,79,...,214.5,120,106,2018,TOR_vs_WAS_42017,2,TOR_vs_WAS_42017_2018-04-27,TOR,4,2–4
1338,42017,1610612761,TOR,Toronto Raptors,41700106,TOR @ WAS,W,240,40,90,...,2,-140,2,2018,TOR_vs_WAS_42017,4,TOR_vs_WAS_42017_2018-04-27,WAS,2,4–2

In [118]:
team_with_spreads.to_csv('team_with_spreads.csv', index=False)

In [119]:
team_with_spreads.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE', 'GAME_DATE',
       'HOME_AWAY', 'Rot', 'VH', 'Team', '1st', '2nd', '3rd', '4th', 'Final',
       'Open', 'Close', 'ML', '2H', 'Year', 'SERIES_ID', 'SERIES_WINS',
       'GAME_KEY', 'OPPONENT_ABBREVIATION', 'OPPONENT_SERIES_WINS',
       'SERIES_STANDING'],
      dtype='object')